StoreApp/Controllers/SalesController.cs
using AutoMapper;
using StoreApp.Models;
using StoreApp.Utils;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StoreApp.Controllers
{
    public class SalesController : Controller
    {
        private ApplicationUserManager _userManager;
        private IStoreRepository _storeRepository;

        public SalesController(ApplicationUserManager userManager, IStoreRepository storeRepositry)
        {
            _userManager = userManager;
            _storeRepository = storeRepositry;
            ViewBag.CategoryOptions = _storeRepository.GetCategoryListItems(0, true);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddProduct()
        {


            ViewBag.Categories = new[] { _storeRepository.GetCategoryListItems(0) };

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddProduct(AddProductViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var categories = new List<IEnumerable<SelectListItem>> { _storeRepository.GetCategoryListItems(model.Categories[0].Id) };

                for (var i = 0; i < model.Categories.Count-1; i++)
                {
                    categories.Add(_storeRepository.GetLowerCategories(model.Categories[i].Id, model.Categories[i+1].Id));
                }

                ViewBag.Categories = categories;

                return View(model);
            }

            _storeRepository.AddProduct(model);

            TempData["success"] = "Dodano pomyślnie produkt";

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Search(SearchViewModel model)
        {
            var products = _storeRepository.SearchProductsBy(model);

            ViewBag.Query = model.Query;

            ViewBag.CategoryId = model.Category;

            var categories = _storeRepository.GetCategories();

            ViewBag.Categories = categories;

            ViewBag.Category = model.Category == 0 ? "wszystkie kategorie" : categories.First(c => c.Id == model.Category).Name;

            return View(products);
        }

        [HttpPost]
        [AjaxOnly]
        public ActionResult GetImage(int index)
        {
            ViewBag.Index = index;

            var image = Request.Files[0];

            var path = Server.MapPath("~/Uploads/");

            var guid = Guid.NewGuid();

            var extension = image.FileName.Split('.').Last();

            var targetFolder = Path.Combine(path, guid + "." + extension);

            image.SaveAs(targetFolder);

            var model = new PictureViewModel
            {
                Id = guid,
                Extension = extension
            };

            return PartialView(model);
        }

        [AjaxOnly]
        public ActionResult GetCategories(int? id, int index)
        {
            if (!id.HasValue)
            {
                // w razie wyboru opcji wybierz, dane z kategoriami są niepoprawne

                return Json(new { allcategories = "false" }, JsonRequestBehavior.AllowGet);
            }
            var categories = _storeRepository.GetLowerCategories(id.Value, 0);

            ViewBag.Index = index;



            if (categories.Any())
            {
                // dodaj wyższy szczebel kategorii

                this.Response.Headers.Add("allcategories", "false");

                ViewBag.Categories = new[] { categories };

                ViewBag.Index2 = 0;

                return PartialView("_CategoryPartial", new AddProductViewModel());
            }

            // po wyborze danej kategorii pod parametrem id, jeśli do tej kategorii nie ma przypisanych niższych kategorii, dane z kategoriami są poprawne

            return Json(new { allcategories = "true" }, JsonRequestBehavior.AllowGet); ;
        }
    }
}

StoreApp/Views/Shared/_CategoriesPartial.cshtml
@model IEnumerable<StoreApp.Models.CategoryViewModel>

<div class="col-sm-3 col-xs-12">
    <div class="panel panel-default">
        <div class="panel-heading">Kategorie</div>
        @Html.Partial("_CategoryLevel", Model)
    </div>
</div>

StoreApp/Views/Shared/_CategoryLevel.cshtml
@model IEnumerable<StoreApp.Models.CategoryViewModel>


<ul>
    @foreach (var category in Model)
    {

        <li>
            @if (category.LowerCategories.Any())
            {
                @:[<a href="#" class="categorynode"><span class="glyphicon glyphicon-plus"></span></a>]
            }
            @Html.ActionLink(category.Name, "GetProducts", new { categoryId = category.Id })
        </li>
        if (category.LowerCategories.Any())
        {
            var categoryIds = ViewBag.CategoryIds;

                <li @if (categoryIds== null || categoryIds != null && ((int[])categoryIds).Any(id => id != category.Id))
                {<text>class= "hidden"</text>}>

                @Html.Partial("_CategoryLevel", category.LowerCategories)

                </li>
        }
    }
</ul>

StoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sklep wielobranżowy</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @{
        if (TempData["modelState"] != null)
        {
            ViewData.ModelState.Merge((ModelStateDictionary)TempData["modelState"]);
        }
    }
    @Html.Partial("_LoginDialog", TempData["model"] ?? new StoreApp.Models.LoginViewModel())
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sklep internetowy", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Strona główna", "Index", "Home")</li>
                    <li>@Html.ActionLink("O sklepie", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_SearchPartial", new StoreApp.Models.SearchViewModel())
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <h1>Sklep wielobranżowy</h1>


            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sklep wielobranżowy</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script>
        $(".categorynode").bind("click", function () {

            var $sign = $(this).children("span");

            $(this).parent().next().toggleClass("hidden");

            $sign.toggleClass("glyphicon-plus").toggleClass("glyphicon-minus");


        });

        $("#login").dialog({
            title: "Zaloguj się",
            buttons: [
                {
                    text: "Zamknij",
                    click: function () {
                        $(this).dialog("close");
                    }
                }
            ],
            modal: true,
            resizable: false,
            show: "slideDown",
            hide: "slideUp",
            draggable: false,
            autoOpen: @(TempData["autoOpen"] != null ? 1 : 0)
        });

        $("#loginLink").bind("click", function () {

            $("#login").dialog("open");

        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

StoreApp/Views/Shared/_LoginDialog.cshtml
@model StoreApp.Models.LoginViewModel

<section id="login" style="display: none;">
    @using (Html.BeginForm("Login", "Account", new { ReturnUrl = Request.RawUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.UserName, new { @class = "control-label" })
            <div>
                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Password, new { @class = "control-label" })
            <div>
                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
            </div>
        </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.RememberMe)
                            @Html.LabelFor(m => m.RememberMe)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Zaloguj się" class="btn btn-default" />
                    </div>
                </div>
    }
</section>

StoreApp/Views/Shared/_SearchPartial.cshtml
@using StoreApp.Models
@model SearchViewModel

@using (Html.BeginForm("Search", "Sales", FormMethod.Get, new { @class = "navbar-left navbar-form" }))
{
    <div class="form-group">
        @Html.TextBoxFor(m => m.Query, new { @class= "form-control", placeholder="Szukaj" })

        @Html.DropDownListFor(m => m.Category, (IEnumerable<SelectListItem>)ViewBag.CategoryOptions,
        new { @class= "form-control" })
    </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
}